CREATE TABLE [dbo].[Curso]
(
	CursoId INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	Titulo NVARCHAR(100) NOT NULL,
	AreaId INT NOT NULL,
	Resumen NVARCHAR(MAX) NOT NULL,
	CursoURL NVARCHAR(250) NOT NULL,
	FOREIGN KEY(AreaId) REFERENCES Area(AreaId)
)
